version: 2.0
jobs:
  unit-test:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run:
        name: Gradle test
        command: |
          gradle test
    - store_test_results:
        path: build/test-results
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run:
        name: Gradle jar
        command: gradle jar
    - store_artifacts:
        path: build/libs
        destination: jar

workflows:
  version: 2
  unittest-build:
    jobs:
    - unit-test:
    - build:
